name: Build Checks
on:
  push:
    tags: [M0, M1, M2, M3, M4, M5, M6]

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout tag ${{github.ref_name}}
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Compile source
        run: mvn compile
      - name: Compile tests
        run: mvn test-compile
